spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: 123456

  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8080

mybatis:
  configuration:
    map-underscore-to-camel-case: true

